# Generated by Django 5.1 on 2024-08-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_myuser_tourcategory_alter_product_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
