# Generated by Django 5.1 on 2024-08-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_tourcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tourcategory',
            name='slug',
        ),
    ]
