# Generated by Django 5.1 on 2024-08-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_ecosystemtype_remove_tourcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecosystemtype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
