# Generated by Django 5.1 on 2024-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_ecocistem_ecosystem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
